style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/dwenegar/luacov-summary
options:
  commits:
    filters:
      type:
        - breaking
        - feature
        - fix
        - refactor
        - performance
        - maintenance
        - build
        - ci
        - test
        - example
        - doc
        - localization
        - translation
        - accessibility
        - deps
        - misc
  commit_groups:
    sort_by: Custom
    title_maps:
      breaking: ğŸš¨ Breaking Changes
      feature: âœ¨ New Features
      fix: ğŸ› Bug Fixes
      refactor: â™»ï¸ Refactoring
      performance: âš¡ï¸ Performance
      maintenance: ğŸ§° Maintenance
      build: ğŸ“¦ Build
      ci: ğŸ§° Maintenance
      test: ğŸš¦ Tests
      example: ğŸ›  Examples
      doc: ğŸ“š Documentation
      localization: ğŸŒ Localization
      accessibility: â™¿ï¸ Accessibility
      deps: ğŸ“¦ Dependencies
      chore: ğŸ— Chores
    title_order:
      - breaking
      - feature
      - fix
      - refactor
      - performance
      - maintenance
      - build
      - ci
      - test
      - example
      - doc
      - docs
      - localization
      - translation
      - accessibility
      - deps
      - misc
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
